name: test

on:
    push:
        branches:
          - main
          - develop

    pull_request:
        branches:
          - main
          - develop

env:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_ENV_HINTS: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Versions
            run: |
                swift --version
          - name: Swift Test
            run: |
                swift test
